### ISSUE TITLE
I was playing in the UI

### ISSUE THREAD

**Issue by tgmarinho** [ezranbayantemur/covid-19-app#1]
![Screenshot_2020-03-31-19-08-49-880_com coronatest](https://user-images.githubusercontent.com/380327/78083885-c965f100-7384-11ea-9057-8a3dea5c7f30.jpg)
![Screenshot_2020-03-31-19-09-45-440_com coronatest](https://user-images.githubusercontent.com/380327/78083894-d08cff00-7384-11ea-8f9f-7a2b4a58d599.jpg)
![Screenshot_2020-03-31-19-09-55-530_com coronatest](https://user-images.githubusercontent.com/380327/78083895-d256c280-7384-11ea-825f-ec70308aea1e.jpg)

[Code:](https://github.com/tgmarinho/covid-19-app
)
Sorry, I changed to Portuguese, my native language! 

Just sharing how it became! Thank you!  =) I enjoyed your project!

**Comment by ezranbayantemur** [comment]
Hello @tgmarinho, it looks great!
Happy to know you like the project, keep it rock! 😎
